version: '3.8'
services:
  app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: npm run dev
    environment:
      - NODE_ENV=development
